### PR TITLE
added the favicon

### PR DESCRIPTION
**Pull request by Natrosvili**
Hello there, I've added the favicon. I hope it looks great :).

### CODE REVIEW

**Review by actyvystom — COMMENTED** [review]
🤔 Hm... your changes seem to have nothing to do with your favicon or do I misunderstand something?

**Comment by Natrosvili** [comment]
> 🤔 Hm... your changes seem to have nothing to do with your favicon or do I misunderstand something?

Oh, as I expected. I pushed the first changes on the main by mistake and then pushed this PR. I've made the changes in the index.js and you can see the icon in the first vercel.

**Comment by actyvystom** [comment]
I did see it on vercel, but I was wondering to not find it in the PR... Anyway, I blame capstone finishing panic for it, no worries ;)

**Comment by Natrosvili** [comment]
> I did see it on vercel, but I was wondering to not find it in the PR... Anyway, I blame capstone finishing panic for it, no worries ;)

Thank you Thomas. It won't happen again :)

**Pull request merged**
